### ISSUE TITLE
Conflicts with the "Bring Out Submenu of Power Off Button" extension

### ISSUE THREAD

**Issue by internauta2000** [d-go/quick-settings-avatar#10]
Thanks for your great job, really beautiful... This extension conflicts with the Bring Out Submenu of Power Off Button extension and does not allow it to run correctly, I personally talked with the developer and informs me that the problem does not originate in your code ... could you check its extension and seek incompatibility?

**Comment by d-go** [comment]
Hi, @internauta2000, thanks for reaching out and sorry for my delayed response. I'll take a look into it in the upcoming days and will keep you posted, in case the issue originates in the QSA extension will work on the fix.

**Comment by d-go** [comment]
In the meantime, could you better describe the issue/conflict you are experiencing? and if possible the steps to reproduce it, it will be useful also the gnome version you're using and the linux distribution.

**Comment by d-go** [comment]
Hi, @internauta2000 , I did take a look at the conflict, some of the issues I noticed having both extensions enabled is that sometimes the Bring Out extension does not show/hide correctly some of the items or the order is not correct, while inspecting the source code, I noticed that it extracts some of the settings items based only on the index like in this line: https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout/blob/main/BringoutMenu.js#L36, this is relying purely in the positions in the menu list, so, if the QSA extensions runs first and adds the item in the menu, it will break the logic based on index run in the Bring Out extension, unfortunately this is not something that can be fixed in the QSA side, it should be fixed in the Bring Out extension by ensuring the elements it removes adds are the ones they expect, the code owner could take this as an example for that:  https://github.com/d-go/quick-settings-avatar/blob/main/extension.js#L190
